repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [ "--line-length=88" ]
        entry: black --config ./.black --exclude=".venv\*"

  - repo: https://github.com/PyCQA/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        additional_dependencies: [ "flake8-pyproject" ]
        args: [ "--exclude=.git,__pycache__,migrations,node_modules,.venv,*/migrations/*,--max-line-length=88", "--select=E,F,W,C90" ]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
